
import javax.swing.JOptionPane;

// Luiz Felipe Feranandes Ramos - RA: 2767112
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author lipf2
 */
public class FormRelDoador extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FormRelDoador.class.getName());
    //MÉTODO SINGLETON
    private static FormRelDoador instancia;

    public static FormRelDoador getInstance() {
        if (instancia == null) {
            instancia = new FormRelDoador();
        }
        instancia.atualizarTabela();
        return instancia;
    }

    /**
     * Creates new form FormRelDoador
     */
    private FormRelDoador() {
        initComponents();
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        btnAlterar.addActionListener(evt -> alterarSelecionado());
        btnExcluir.addActionListener(evt -> excluirSelecionado());
    }

    @Override
    public void dispose() {
        super.dispose();
        instancia = null;
    }

    public void atualizarTabela() {
        javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) tbDoadorGeral.getModel();
        model.setRowCount(0);
        for (Doador d : BDHospital.getInstance().listarDoadores()) {
            model.addRow(new Object[]{
                d.getNome(),
                d.getIdade(),
                d.getCpf(),
                d.getSexo(),
                d.getEmail(),
                d.getOrgao(),
                d.getDataCadastro()
            });
        }
    }

    private void alterarSelecionado() {
        int row = tbDoadorGeral.getSelectedRow();
        if (row < 0) { javax.swing.JOptionPane.showMessageDialog(this, "Selecione um doador"); return; }
        String cpf = String.valueOf(tbDoadorGeral.getValueAt(row, 2));
        Doador d = BDHospital.getInstance().buscarDoadorPorCpf(cpf);
        if (d == null) { javax.swing.JOptionPane.showMessageDialog(this, "Doador não encontrado"); return; }
        FormCadDoador form = FormCadDoador.getInstance();
        form.prepararEdicao(d);
        form.setVisible(true);
    }

    private void excluirSelecionado() {
        int row = tbDoadorGeral.getSelectedRow();
        if (row < 0) { javax.swing.JOptionPane.showMessageDialog(this, "Selecione um doador"); return; }
        String cpf = String.valueOf(tbDoadorGeral.getValueAt(row, 2));
        int resp = javax.swing.JOptionPane.showConfirmDialog(this, "Excluir doador selecionado?", "Confirmação", javax.swing.JOptionPane.YES_NO_OPTION);
        if (resp != javax.swing.JOptionPane.YES_OPTION) return;
        BDHospital.getInstance().removerDoador(cpf);
        atualizarTabela();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbDoadorGeral = new javax.swing.JTable();
        pnlAcoes = new javax.swing.JPanel();
        btnAlterar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Relatório Geral Doador");

        tbDoadorGeral.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Nome", "Idade", "CPF", "Sexo", "Email", "Orgão", "Data Cadastro"
            }
        ));
        tbDoadorGeral.setToolTipText("");
        jScrollPane1.setViewportView(tbDoadorGeral);

        btnAlterar.setText("Alterar");

        btnExcluir.setText("Excluir");

        javax.swing.GroupLayout pnlAcoesLayout = new javax.swing.GroupLayout(pnlAcoes);
        pnlAcoes.setLayout(pnlAcoesLayout);
        pnlAcoesLayout.setHorizontalGroup(
            pnlAcoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAcoesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnAlterar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnExcluir)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlAcoesLayout.setVerticalGroup(
            pnlAcoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAcoesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlAcoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAlterar)
                    .addComponent(btnExcluir))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 569, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnlAcoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 6, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlAcoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public void sair(){
        int resp = JOptionPane.showConfirmDialog(
            this,
            "Deseja realmente sair?",
            "Saída",
            JOptionPane.YES_NO_OPTION
        );
        if(resp == JOptionPane.YES_OPTION){
            dispose();
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FormRelDoador().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel pnlAcoes;
    private javax.swing.JTable tbDoadorGeral;
    // End of variables declaration//GEN-END:variables

    
}
