
import javax.swing.JOptionPane;

// Luiz Felipe Feranandes Ramos - RA: 2767112
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author lipf2
 */
public class FormCadDoador extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FormCadDoador.class.getName());

    /**
     * Creates new form FormCadDoador
     */
    //MÉTODO SINGLETON
    private static FormCadDoador instancia;
    private Doador emEdicao;

    public static FormCadDoador getInstance() {
        if (instancia == null) {
            instancia = new FormCadDoador();
        }
        return instancia;
    }

    private FormCadDoador() {
        initComponents();
        // listeners
        btnCadastro.addActionListener(evt -> {
            Doador d = emEdicao != null ? emEdicao : new Doador();
            d.setNome(inpNomeDoador.getText());
            try {
                int idade = Integer.parseInt(inpIdadeDoador.getText());
                d.setIdade(idade);
            } catch (NumberFormatException nfe) {
                javax.swing.JOptionPane.showMessageDialog(this, "Idade inválida (não é número)");
                return;
            } catch (IdadeInvalidaException ex) {
                javax.swing.JOptionPane.showMessageDialog(this, ex.getMessage());
                return;
            }
            d.setCpf(inpCpfDoador.getText());
            d.setSexo(cbSexoDoador.getSelectedItem().toString().charAt(0));
            d.setEmail(inpOrgaoDoador.getText());
            // usar campo existente como órgão (form foi criado originalmente com outro nome)
            d.setOrgao(inpOrgaoDoador.getText());
            d.setDataCadastro(java.time.LocalDate.now().toString());
            if (emEdicao == null) {
                BDHospital.getInstance().inserirDoador(d);
                javax.swing.JOptionPane.showMessageDialog(this, "Doador cadastrado com sucesso!");
            } else {
                BDHospital.getInstance().atualizarDoador(d);
                javax.swing.JOptionPane.showMessageDialog(this, "Doador atualizado com sucesso!");
            }
            limparCampos();
        });

        btnCancelar.addActionListener(evt -> {
            this.dispose();
            instancia = null;
            emEdicao = null;
        });

        
    }

            public void prepararEdicao(Doador existente) {
                if (existente == null) return;
                emEdicao = existente;
                inpNomeDoador.setText(existente.getNome());
                inpIdadeDoador.setText(String.valueOf(existente.getIdade()));
                inpCpfDoador.setText(existente.getCpf());
                inpCpfDoador.setEnabled(false);
                cbSexoDoador.setSelectedItem(String.valueOf(existente.getSexo()));
                inpEmailDoador.setText(existente.getEmail());
                inpOrgaoDoador.setText(existente.getOrgao());
                btnCadastro.setText("Salvar");
                this.toFront();
            }

            private void limparCampos() {
                emEdicao = null;
                btnCadastro.setText("Cadastrar");
                inpCpfDoador.setEnabled(true);
                inpNomeDoador.setText(""); inpIdadeDoador.setText(""); inpCpfDoador.setText(""); inpOrgaoDoador.setText("");
                cbSexoDoador.setSelectedIndex(0); inpOrgaoDoador.setText(""); inpEmailDoador.setText("");
            }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbIdadeDoador = new javax.swing.JLabel();
        inpIdadeDoador = new javax.swing.JTextField();
        lbSexoDoador = new javax.swing.JLabel();
        cbSexoDoador = new javax.swing.JComboBox<>();
        lbCpfDoador = new javax.swing.JLabel();
        inpCpfDoador = new javax.swing.JTextField();
        btnCadastro = new javax.swing.JButton();
        lbNomeDoador = new javax.swing.JLabel();
        btnCancelar = new javax.swing.JButton();
        inpNomeDoador = new javax.swing.JTextField();
        lbEmailDoador = new javax.swing.JLabel();
        lbTipoSanguineoDoador = new javax.swing.JLabel();
        inpOrgaoDoador = new javax.swing.JTextField();
        inpEmailDoador = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastrar Doador");

        lbIdadeDoador.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbIdadeDoador.setText("Idade");

        inpIdadeDoador.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        inpIdadeDoador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inpIdadeDoadorActionPerformed(evt);
            }
        });

        lbSexoDoador.setText("Sexo");

        cbSexoDoador.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "F", "M" }));
        cbSexoDoador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbSexoDoadorActionPerformed(evt);
            }
        });

        lbCpfDoador.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbCpfDoador.setText("CPF: 000.000.000-00");

        inpCpfDoador.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        inpCpfDoador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inpCpfDoadorActionPerformed(evt);
            }
        });

        btnCadastro.setText("Cadastrar");
        btnCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastroActionPerformed(evt);
            }
        });

        lbNomeDoador.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbNomeDoador.setText("Nome");

        btnCancelar.setText("Cancelar");

        inpNomeDoador.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        inpNomeDoador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inpNomeDoadorActionPerformed(evt);
            }
        });

        lbEmailDoador.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbEmailDoador.setText("Email:");

        lbTipoSanguineoDoador.setText("Orgão:");

        inpOrgaoDoador.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        inpOrgaoDoador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inpOrgaoDoadorActionPerformed(evt);
            }
        });

        inpEmailDoador.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        inpEmailDoador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inpEmailDoadorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(inpEmailDoador, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inpNomeDoador, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbCpfDoador)
                            .addComponent(inpCpfDoador, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbIdadeDoador)
                                .addGap(18, 18, 18)
                                .addComponent(lbSexoDoador)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbTipoSanguineoDoador)
                            .addComponent(inpOrgaoDoador)))
                    .addComponent(lbNomeDoador)
                    .addComponent(lbEmailDoador)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(inpIdadeDoador, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(btnCadastro)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnCancelar))
                            .addComponent(cbSexoDoador, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbNomeDoador)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inpNomeDoador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbEmailDoador)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inpEmailDoador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbCpfDoador)
                    .addComponent(lbTipoSanguineoDoador))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inpCpfDoador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inpOrgaoDoador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbSexoDoador)
                    .addComponent(lbIdadeDoador))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbSexoDoador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inpIdadeDoador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCadastro)
                    .addComponent(btnCancelar))
                .addGap(29, 29, 29))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void inpIdadeDoadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inpIdadeDoadorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inpIdadeDoadorActionPerformed

    private void cbSexoDoadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbSexoDoadorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbSexoDoadorActionPerformed

    private void inpCpfDoadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inpCpfDoadorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inpCpfDoadorActionPerformed

    private void inpNomeDoadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inpNomeDoadorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inpNomeDoadorActionPerformed

    private void inpOrgaoDoadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inpOrgaoDoadorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inpOrgaoDoadorActionPerformed

    private void btnCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCadastroActionPerformed

    private void inpEmailDoadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inpEmailDoadorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inpEmailDoadorActionPerformed
    
    public void sair(){
        int resp = JOptionPane.showConfirmDialog(
            this,
            "Deseja realmente sair?",
            "Saída",
            JOptionPane.YES_NO_OPTION
        );
        if(resp == JOptionPane.YES_OPTION){
            dispose();
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> FormCadDoador.getInstance().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastro;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JComboBox<String> cbSexoDoador;
    private javax.swing.JTextField inpCpfDoador;
    private javax.swing.JTextField inpEmailDoador;
    private javax.swing.JTextField inpIdadeDoador;
    private javax.swing.JTextField inpNomeDoador;
    private javax.swing.JTextField inpOrgaoDoador;
    private javax.swing.JLabel lbCpfDoador;
    private javax.swing.JLabel lbEmailDoador;
    private javax.swing.JLabel lbIdadeDoador;
    private javax.swing.JLabel lbNomeDoador;
    private javax.swing.JLabel lbSexoDoador;
    private javax.swing.JLabel lbTipoSanguineoDoador;
    // End of variables declaration//GEN-END:variables
}
