// Luiz Felipe Feranandes Ramos - RA: 2767112
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author lipf2
 */
public class FormDoador extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FormDoador.class.getName());

    /**
     * Creates new form FormDoador
     */
    //MÉTODO SINGLETON
    private static FormDoador instancia;

    public static FormDoador getInstance() {
        if (instancia == null) {
            instancia = new FormDoador();
        }
        return instancia;
    }

    private FormDoador() {
        initComponents();
        // listeners
        btnCadastro.addActionListener(evt -> {
            Doador d = new Doador();
            d.setNome(inpNomeDoador.getText());
            try {
                int idade = Integer.parseInt(inpIdadeDoador.getText());
                d.setIdade(idade);
            } catch (NumberFormatException nfe) {
                javax.swing.JOptionPane.showMessageDialog(this, "Idade inválida (não é número)");
                return;
            } catch (IdadeInvalidaException ex) {
                javax.swing.JOptionPane.showMessageDialog(this, ex.getMessage());
                return;
            }
            d.setCpf(inpCpfDoador.getText());
            d.setSexo(cbSexoDoador.getSelectedItem().toString().charAt(0));
            d.setEmail(inpOrgaoDoador.getText());
            // usar campo existente como órgão (form foi criado originalmente com outro nome)
            d.setOrgao(inpOrgaoDoador.getText());
            d.setDataCadastro(java.time.LocalDate.now().toString());
            BDHospital.getInstance().inserirDoador(d);
            javax.swing.JOptionPane.showMessageDialog(this, "Doador cadastrado com sucesso!");
            // limpar
            inpNomeDoador.setText(""); inpIdadeDoador.setText(""); inpCpfDoador.setText(""); inpOrgaoDoador.setText(""); cbDoencaDoador.setSelectedIndex(0);
            cbSexoDoador.setSelectedIndex(0); inpOrgaoDoador.setText("");
        });

        btnCancelar.addActionListener(evt -> {
            this.dispose();
            instancia = null;
        });

        btnCadPaciente.addActionListener(evt -> FormPaciente.getInstance().setVisible(true));
        btnCadMedico.addActionListener(evt -> FormMedico.getInstance().setVisible(true));
        btnRelDoador.addActionListener(evt -> {
            java.util.List<Doador> list = BDHospital.getInstance().listarDoadores();
            StringBuilder sb = new StringBuilder();
            for (Doador dd : list) sb.append(dd.listar()).append('\n');
            javax.swing.JOptionPane.showMessageDialog(this, sb.length()==0?"Nenhum doador cadastrado":sb.toString());
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbIdadeDoador = new javax.swing.JLabel();
        inpIdadeDoador = new javax.swing.JTextField();
        lbSexoDoador = new javax.swing.JLabel();
        cbSexoDoador = new javax.swing.JComboBox<>();
        lbCpfDoador = new javax.swing.JLabel();
        inpCpfDoador = new javax.swing.JTextField();
        btnCadastro = new javax.swing.JButton();
        lbNomeDoador = new javax.swing.JLabel();
        btnCancelar = new javax.swing.JButton();
        inpNomeDoador = new javax.swing.JTextField();
        lbEmailDoador = new javax.swing.JLabel();
        lbTipoSanguineoDoador = new javax.swing.JLabel();
        inpOrgaoDoador = new javax.swing.JTextField();
        lbDoencaDoador = new javax.swing.JLabel();
        cbDoencaDoador = new javax.swing.JComboBox<>();
        inpEmailDoador1 = new javax.swing.JTextField();
        barMenu = new javax.swing.JMenuBar();
        btnMenu = new javax.swing.JMenu();
        cadMenu = new javax.swing.JMenu();
        btnCadPaciente = new javax.swing.JMenuItem();
        btnCadDoador = new javax.swing.JMenuItem();
        btnCadMedico = new javax.swing.JMenuItem();
        btnRelatorios = new javax.swing.JMenu();
        btnRelPaciente = new javax.swing.JMenuItem();
        btnRelDoador = new javax.swing.JMenuItem();
        btnRelMedico = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbIdadeDoador.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbIdadeDoador.setText("Idade");

        inpIdadeDoador.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        inpIdadeDoador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inpIdadeDoadorActionPerformed(evt);
            }
        });

        lbSexoDoador.setText("Sexo");

        cbSexoDoador.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "F", "M" }));
        cbSexoDoador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbSexoDoadorActionPerformed(evt);
            }
        });

        lbCpfDoador.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbCpfDoador.setText("CPF: 000.000.000-00");

        inpCpfDoador.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        inpCpfDoador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inpCpfDoadorActionPerformed(evt);
            }
        });

        btnCadastro.setText("Cadastrar");
        btnCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastroActionPerformed(evt);
            }
        });

        lbNomeDoador.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbNomeDoador.setText("Nome");

        btnCancelar.setText("Cancelar");

        inpNomeDoador.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        inpNomeDoador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inpNomeDoadorActionPerformed(evt);
            }
        });

        lbEmailDoador.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbEmailDoador.setText("Email:");

        lbTipoSanguineoDoador.setText("Orgão:");

        inpOrgaoDoador.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        inpOrgaoDoador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inpOrgaoDoadorActionPerformed(evt);
            }
        });

        lbDoencaDoador.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbDoencaDoador.setText("Portador de Doença:");

        cbDoencaDoador.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SIm", "Não" }));

        inpEmailDoador1.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        inpEmailDoador1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inpEmailDoador1ActionPerformed(evt);
            }
        });

        btnMenu.setText("Menu");
        btnMenu.setActionCommand("");

        cadMenu.setText("Cadastrar");

        btnCadPaciente.setText("Pacientes");
        btnCadPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadPacienteActionPerformed(evt);
            }
        });
        cadMenu.add(btnCadPaciente);

        btnCadDoador.setText("Doadores");
        btnCadDoador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadDoadorActionPerformed(evt);
            }
        });
        cadMenu.add(btnCadDoador);

        btnCadMedico.setText("Médicos");
        btnCadMedico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadMedicoActionPerformed(evt);
            }
        });
        cadMenu.add(btnCadMedico);

        btnMenu.add(cadMenu);

        barMenu.add(btnMenu);

        btnRelatorios.setText("Relatórios");

        btnRelPaciente.setText("Pacientes");
        btnRelPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRelPacienteActionPerformed(evt);
            }
        });
        btnRelatorios.add(btnRelPaciente);

        btnRelDoador.setText("Doadores");
        btnRelatorios.add(btnRelDoador);

        btnRelMedico.setText("Médicos");
        btnRelatorios.add(btnRelMedico);

        barMenu.add(btnRelatorios);

        setJMenuBar(barMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(137, 137, 137)
                .addComponent(btnCadastro)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCancelar)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbEmailDoador)
                                .addGap(225, 225, 225))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(inpEmailDoador1, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbTipoSanguineoDoador)
                            .addComponent(inpOrgaoDoador, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(55, 55, 55))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(inpCpfDoador, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lbCpfDoador)
                                        .addGap(83, 83, 83)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbDoencaDoador)
                                    .addComponent(cbDoencaDoador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbNomeDoador)
                                    .addComponent(inpNomeDoador, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lbIdadeDoador, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(inpIdadeDoador, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(lbSexoDoador)
                                        .addGap(26, 26, 26))
                                    .addComponent(cbSexoDoador, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(135, 135, 135))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lbNomeDoador)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(inpNomeDoador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lbIdadeDoador)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(inpIdadeDoador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbSexoDoador)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbSexoDoador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbEmailDoador)
                    .addComponent(lbTipoSanguineoDoador))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inpEmailDoador1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inpOrgaoDoador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbDoencaDoador)
                    .addComponent(lbCpfDoador))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inpCpfDoador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbDoencaDoador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCadastro)
                    .addComponent(btnCancelar))
                .addGap(38, 38, 38))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCadPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadPacienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCadPacienteActionPerformed

    private void btnCadDoadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadDoadorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCadDoadorActionPerformed

    private void btnCadMedicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadMedicoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCadMedicoActionPerformed

    private void btnRelPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRelPacienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRelPacienteActionPerformed

    private void inpIdadeDoadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inpIdadeDoadorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inpIdadeDoadorActionPerformed

    private void cbSexoDoadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbSexoDoadorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbSexoDoadorActionPerformed

    private void inpCpfDoadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inpCpfDoadorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inpCpfDoadorActionPerformed

    private void inpNomeDoadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inpNomeDoadorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inpNomeDoadorActionPerformed

    private void inpOrgaoDoadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inpOrgaoDoadorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inpOrgaoDoadorActionPerformed

    private void btnCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCadastroActionPerformed

    private void inpEmailDoador1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inpEmailDoador1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inpEmailDoador1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> FormDoador.getInstance().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar barMenu;
    private javax.swing.JMenuItem btnCadDoador;
    private javax.swing.JMenuItem btnCadMedico;
    private javax.swing.JMenuItem btnCadPaciente;
    private javax.swing.JButton btnCadastro;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JMenu btnMenu;
    private javax.swing.JMenuItem btnRelDoador;
    private javax.swing.JMenuItem btnRelMedico;
    private javax.swing.JMenuItem btnRelPaciente;
    private javax.swing.JMenu btnRelatorios;
    private javax.swing.JMenu cadMenu;
    private javax.swing.JComboBox<String> cbDoencaDoador;
    private javax.swing.JComboBox<String> cbSexoDoador;
    private javax.swing.JTextField inpCpfDoador;
    private javax.swing.JTextField inpEmailDoador1;
    private javax.swing.JTextField inpIdadeDoador;
    private javax.swing.JTextField inpNomeDoador;
    private javax.swing.JTextField inpOrgaoDoador;
    private javax.swing.JLabel lbCpfDoador;
    private javax.swing.JLabel lbDoencaDoador;
    private javax.swing.JLabel lbEmailDoador;
    private javax.swing.JLabel lbIdadeDoador;
    private javax.swing.JLabel lbNomeDoador;
    private javax.swing.JLabel lbSexoDoador;
    private javax.swing.JLabel lbTipoSanguineoDoador;
    // End of variables declaration//GEN-END:variables
}
