
// NetBeans IDE 27
// Luiz Felipe Feranandes Ramos - RA 2767112
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author lipf2
 */
public class FormPrincipal extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FormPrincipal.class.getName());
    //MÉTODO SINGLETON
    private static FormPrincipal instancia;

    public static FormPrincipal getInstance() {
        if (instancia == null) {
            instancia = new FormPrincipal();
        }
        return instancia;
    }

    /**
     * Creates new form FormPrincipal
     */
    private FormPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        barMenu = new javax.swing.JMenuBar();
        btnMenu = new javax.swing.JMenu();
        cadMenu = new javax.swing.JMenu();
        btnCadPaciente = new javax.swing.JMenuItem();
        btnCadDoador = new javax.swing.JMenuItem();
        btnCadMedico = new javax.swing.JMenuItem();
        btnSair = new javax.swing.JMenuItem();
        btnRelatorios = new javax.swing.JMenu();
        btnRelPaciente = new javax.swing.JMenuItem();
        btnRelDoador = new javax.swing.JMenuItem();
        btnRelMedico = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("LifeGen");

        jLabel1.setText("jLabel1");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel2.setText("Tela inicial do Projeto");

        btnMenu.setText("Menu");
        btnMenu.setActionCommand("");

        cadMenu.setText("Cadastrar");

        btnCadPaciente.setText("Pacientes");
        btnCadPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadPacienteActionPerformed(evt);
            }
        });
        cadMenu.add(btnCadPaciente);

        btnCadDoador.setText("Doadores");
        btnCadDoador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadDoadorActionPerformed(evt);
            }
        });
        cadMenu.add(btnCadDoador);

        btnCadMedico.setText("Médicos");
        btnCadMedico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadMedicoActionPerformed(evt);
            }
        });
        cadMenu.add(btnCadMedico);

        btnMenu.add(cadMenu);

        btnSair.setText("Sair");
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });
        btnMenu.add(btnSair);

        barMenu.add(btnMenu);

        btnRelatorios.setText("Relatórios");

        btnRelPaciente.setText("Pacientes");
        btnRelPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRelPacienteActionPerformed(evt);
            }
        });
        btnRelatorios.add(btnRelPaciente);

        btnRelDoador.setText("Doadores");
        btnRelatorios.add(btnRelDoador);

        btnRelMedico.setText("Médicos");
        btnRelatorios.add(btnRelMedico);

        barMenu.add(btnRelatorios);

        setJMenuBar(barMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(90, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(80, 80, 80))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(102, 102, 102)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(135, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCadMedicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadMedicoActionPerformed
        FormMedico.getInstance().setVisible(true);
    }//GEN-LAST:event_btnCadMedicoActionPerformed

    private void btnCadDoadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadDoadorActionPerformed
        FormDoador.getInstance().setVisible(true);
    }//GEN-LAST:event_btnCadDoadorActionPerformed

    private void btnCadPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadPacienteActionPerformed
        FormPaciente.getInstance().setVisible(true);
    }//GEN-LAST:event_btnCadPacienteActionPerformed

    private void btnRelPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRelPacienteActionPerformed
        java.util.List<Paciente> list = BDHospital.getInstance().listarPacientes();
        StringBuilder sb = new StringBuilder();
        for (Paciente p : list) sb.append(p.listar()).append('\n');
        JOptionPane.showMessageDialog(this, sb.length() == 0 ? "Nenhum paciente cadastrado" : sb.toString());
    }//GEN-LAST:event_btnRelPacienteActionPerformed

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        sair();
    }//GEN-LAST:event_btnSairActionPerformed

    public void sair(){
        int resp = JOptionPane.showConfirmDialog(
            this,
            "Deseja realmente sair?",
            "Saída",
            JOptionPane.YES_NO_OPTION
        );
        if(resp == JOptionPane.YES_OPTION){
            dispose();
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> FormPrincipal.getInstance().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar barMenu;
    private javax.swing.JMenuItem btnCadDoador;
    private javax.swing.JMenuItem btnCadMedico;
    private javax.swing.JMenuItem btnCadPaciente;
    private javax.swing.JMenu btnMenu;
    private javax.swing.JMenuItem btnRelDoador;
    private javax.swing.JMenuItem btnRelMedico;
    private javax.swing.JMenuItem btnRelPaciente;
    private javax.swing.JMenu btnRelatorios;
    private javax.swing.JMenuItem btnSair;
    private javax.swing.JMenu cadMenu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables

    private void setDefaultCloseOparation(int EXIT_ON_CLOSE) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
