
import javax.swing.JOptionPane;

// Luiz Felipe Feranandes Ramos - RA: 2767112
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author lipf2
 */
public class FormCadConsulta extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FormCadConsulta.class.getName());

    /**
     * Creates new form FormCadConsulta
     */
    //MÉTODO SINGLETON
    private static FormCadConsulta instancia;

    public static FormCadConsulta getInstance() {
        if (instancia == null) {
            instancia = new FormCadConsulta();
        }
        instancia.carregarCombos();
        return instancia;
    }

    private FormCadConsulta() {
        initComponents();
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnCancelar = new javax.swing.JButton();
        cbMedico = new javax.swing.JComboBox<>();
        lbNomePaciente = new javax.swing.JLabel();
        lbHoraConsulta = new javax.swing.JLabel();
        lbDataConsulta = new javax.swing.JLabel();
        cbPaciente = new javax.swing.JComboBox<>();
        btnCadastro = new javax.swing.JButton();
        lbNomeMedico = new javax.swing.JLabel();
        inpDataConsulta = new javax.swing.JTextField();
        inpHoraConsulta = new javax.swing.JTextField();

        setTitle("Casdastrar Consulta");

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        cbMedico.setToolTipText("Selecione o médico");

        lbNomePaciente.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbNomePaciente.setText("Paciente:");

        lbHoraConsulta.setText("Hora");

        lbDataConsulta.setText("Data");

        cbPaciente.setToolTipText("Selecione o paciente");

        btnCadastro.setText("Cadastrar");
        btnCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastroActionPerformed(evt);
            }
        });

        lbNomeMedico.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbNomeMedico.setText("Médico:");

        inpDataConsulta.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        inpDataConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inpDataConsultaActionPerformed(evt);
            }
        });

        inpHoraConsulta.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        inpHoraConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inpHoraConsultaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(99, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbNomeMedico)
                            .addComponent(cbMedico, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(lbNomePaciente)
                                .addComponent(cbPaciente, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lbDataConsulta)
                                        .addComponent(inpDataConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(93, 93, 93)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(inpHoraConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lbHoraConsulta)))))
                        .addGap(84, 84, 84))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnCadastro)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnCancelar)
                        .addGap(119, 119, 119))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(49, Short.MAX_VALUE)
                .addComponent(lbNomeMedico)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbMedico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbNomePaciente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbDataConsulta)
                    .addComponent(lbHoraConsulta))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(inpDataConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inpHoraConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCadastro)
                    .addComponent(btnCancelar))
                .addGap(37, 37, 37))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void inpDataConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inpDataConsultaActionPerformed
        // no-op
    }//GEN-LAST:event_inpDataConsultaActionPerformed

    private void inpHoraConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inpHoraConsultaActionPerformed
        // no-op
    }//GEN-LAST:event_inpHoraConsultaActionPerformed

    private void btnCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastroActionPerformed
        Medico medico = (Medico) cbMedico.getSelectedItem();
        Paciente paciente = (Paciente) cbPaciente.getSelectedItem();
        if (medico == null) { javax.swing.JOptionPane.showMessageDialog(this, "Selecione um médico."); return; }
        if (paciente == null) { javax.swing.JOptionPane.showMessageDialog(this, "Selecione um paciente."); return; }
        Consulta c = new Consulta();
        c.setMedico(medico);
        c.setPaciente(paciente);
        c.setData(inpDataConsulta.getText());
        c.setHora(inpHoraConsulta.getText());
        BDHospital.getInstance().inserirConsulta(c);
        javax.swing.JOptionPane.showMessageDialog(this, "Consulta cadastrada com sucesso!");
        cbMedico.setSelectedIndex(-1); cbPaciente.setSelectedIndex(-1); inpDataConsulta.setText(""); inpHoraConsulta.setText("");
    }//GEN-LAST:event_btnCadastroActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.dispose();
        instancia = null;
    }//GEN-LAST:event_btnCancelarActionPerformed

    
    public void sair(){
        int resp = JOptionPane.showConfirmDialog(
            this,
            "Deseja realmente sair?",
            "Saída",
            JOptionPane.YES_NO_OPTION
        );
        if(resp == JOptionPane.YES_OPTION){
            dispose();
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> FormCadConsulta.getInstance().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastro;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JComboBox<Medico> cbMedico;
    private javax.swing.JComboBox<Paciente> cbPaciente;
    private javax.swing.JTextField inpDataConsulta;
    private javax.swing.JTextField inpHoraConsulta;
    private javax.swing.JLabel lbDataConsulta;
    private javax.swing.JLabel lbHoraConsulta;
    private javax.swing.JLabel lbNomeMedico;
    private javax.swing.JLabel lbNomePaciente;
    // End of variables declaration//GEN-END:variables

    private void carregarCombos() {
        javax.swing.DefaultComboBoxModel<Medico> medModel = new javax.swing.DefaultComboBoxModel<>();
        for (Medico m : BDHospital.getInstance().listarMedicos()) {
            medModel.addElement(m);
        }
        cbMedico.setModel(medModel);
        cbMedico.setSelectedIndex(medModel.getSize() > 0 ? 0 : -1);

        javax.swing.DefaultComboBoxModel<Paciente> pacModel = new javax.swing.DefaultComboBoxModel<>();
        for (Paciente p : BDHospital.getInstance().listarPacientes()) {
            pacModel.addElement(p);
        }
        cbPaciente.setModel(pacModel);
        cbPaciente.setSelectedIndex(pacModel.getSize() > 0 ? 0 : -1);
    }
}
