
import javax.swing.JOptionPane;

// Luiz Felipe Feranandes Ramos - RA: 2767112
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author lipf2
 */
public class FormRelPaciente extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FormRelPaciente.class.getName());
    //MÉTODO SINGLETON
    private static FormRelPaciente instancia;

    public static FormRelPaciente getInstance() {
        if (instancia == null) {
            instancia = new FormRelPaciente();
        }
        instancia.atualizarTabela();
        return instancia;
    }

    /**
     * Creates new form FormRelPaciente
     */
    private FormRelPaciente() {
        initComponents();
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    }

    @Override
    public void dispose() {
        super.dispose();
        instancia = null;
    }

    public void atualizarTabela() {
        javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) tbPacienteGeral.getModel();
        model.setRowCount(0);
        for (Paciente p : BDHospital.getInstance().listarPacientes()) {
            model.addRow(new Object[]{
                p.getNome(),
                p.getIdade(),
                p.getCpf(),
                p.getSexo(),
                p.getEmail(),
                p.getDoenca(),
                p.getTipoSanguineo()
            });
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbPacienteGeral = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Relatório Geral Paciente");

        tbPacienteGeral.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Nome", "Idade", "CPF", "Sexo", "Email", "Enfermidade", "Tipo Sanguineo"
            }
        ));
        tbPacienteGeral.setToolTipText("");
        jScrollPane1.setViewportView(tbPacienteGeral);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 327, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    public void sair(){
        int resp = JOptionPane.showConfirmDialog(
            this,
            "Deseja realmente sair?",
            "Saída",
            JOptionPane.YES_NO_OPTION
        );
        if(resp == JOptionPane.YES_OPTION){
            dispose();
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FormRelPaciente().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbPacienteGeral;
    // End of variables declaration//GEN-END:variables
}
