/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author lipf2
 */
public class FormPaciente extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FormPaciente.class.getName());

    /**
     * Creates new form FormPaciente
     */
    public FormPaciente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbNomePaciente = new javax.swing.JLabel();
        inpNomePaciente = new javax.swing.JTextField();
        lbEmailPaciente = new javax.swing.JLabel();
        inpEmailPaciente = new javax.swing.JTextField();
        lbIdadePaciente = new javax.swing.JLabel();
        inpIdadePaciente = new javax.swing.JTextField();
        lbSexoPaciente = new javax.swing.JLabel();
        cbSexoPaciente = new javax.swing.JComboBox<>();
        lbCpfPaciente = new javax.swing.JLabel();
        inpCpfPaciente = new javax.swing.JTextField();
        btnCadastro = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        cbTipoanguineoPaciente = new javax.swing.JComboBox<>();
        lbTipoSanguineoPaciente = new javax.swing.JLabel();
        lbDoencaPaciente = new javax.swing.JLabel();
        inpDoencaPaciente = new javax.swing.JTextField();
        barMenu = new javax.swing.JMenuBar();
        btnMenu = new javax.swing.JMenu();
        cadMenu = new javax.swing.JMenu();
        btnCadPaciente = new javax.swing.JMenuItem();
        btnCadDoador = new javax.swing.JMenuItem();
        btnCadMedico = new javax.swing.JMenuItem();
        btnRelatorios = new javax.swing.JMenu();
        btnRelPaciente = new javax.swing.JMenuItem();
        btnRelDoador = new javax.swing.JMenuItem();
        btnRelMedico = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cadastro de Pacientes");

        lbNomePaciente.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbNomePaciente.setText("Nome");

        inpNomePaciente.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        inpNomePaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inpNomePacienteActionPerformed(evt);
            }
        });

        lbEmailPaciente.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbEmailPaciente.setText("Email:");

        inpEmailPaciente.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        inpEmailPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inpEmailPacienteActionPerformed(evt);
            }
        });

        lbIdadePaciente.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbIdadePaciente.setText("Idade");

        inpIdadePaciente.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        inpIdadePaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inpIdadePacienteActionPerformed(evt);
            }
        });

        lbSexoPaciente.setText("Sexo");

        cbSexoPaciente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "F", "M" }));
        cbSexoPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbSexoPacienteActionPerformed(evt);
            }
        });

        lbCpfPaciente.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbCpfPaciente.setText("CPF: 000.000.000-00");

        inpCpfPaciente.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        inpCpfPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inpCpfPacienteActionPerformed(evt);
            }
        });

        btnCadastro.setText("Cadastrar");

        btnCancelar.setText("Cancelar");

        cbTipoanguineoPaciente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A+", "A-", "B+", "B-", "AB+", "AB-", "O+", "O-" }));
        cbTipoanguineoPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbTipoanguineoPacienteActionPerformed(evt);
            }
        });

        lbTipoSanguineoPaciente.setText("Tipo Sanguineo:");

        lbDoencaPaciente.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbDoencaPaciente.setText("Doença:");

        inpDoencaPaciente.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        inpDoencaPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inpDoencaPacienteActionPerformed(evt);
            }
        });

        btnMenu.setText("Menu");
        btnMenu.setActionCommand("");

        cadMenu.setText("Cadastrar");

        btnCadPaciente.setText("Pacientes");
        btnCadPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadPacienteActionPerformed(evt);
            }
        });
        cadMenu.add(btnCadPaciente);

        btnCadDoador.setText("Doadores");
        btnCadDoador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadDoadorActionPerformed(evt);
            }
        });
        cadMenu.add(btnCadDoador);

        btnCadMedico.setText("Médicos");
        btnCadMedico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadMedicoActionPerformed(evt);
            }
        });
        cadMenu.add(btnCadMedico);

        btnMenu.add(cadMenu);

        barMenu.add(btnMenu);

        btnRelatorios.setText("Relatórios");

        btnRelPaciente.setText("Pacientes");
        btnRelPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRelPacienteActionPerformed(evt);
            }
        });
        btnRelatorios.add(btnRelPaciente);

        btnRelDoador.setText("Doadores");
        btnRelatorios.add(btnRelDoador);

        btnRelMedico.setText("Médicos");
        btnRelatorios.add(btnRelMedico);

        barMenu.add(btnRelatorios);

        setJMenuBar(barMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnCadastro)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnCancelar)
                        .addGap(116, 116, 116))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbNomePaciente)
                                    .addComponent(inpNomePaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lbIdadePaciente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(inpIdadePaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(lbSexoPaciente)
                                        .addGap(26, 26, 26))
                                    .addComponent(cbSexoPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbEmailPaciente)
                                    .addComponent(inpEmailPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbTipoSanguineoPaciente)
                                    .addComponent(cbTipoanguineoPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(inpCpfPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lbCpfPaciente)
                                        .addGap(83, 83, 83)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbDoencaPaciente)
                                    .addComponent(inpDoencaPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(21, 21, 21))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(lbNomePaciente)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(inpNomePaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(lbIdadePaciente)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(inpIdadePaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbSexoPaciente)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbSexoPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbEmailPaciente)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(inpEmailPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbTipoSanguineoPaciente)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbTipoanguineoPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbDoencaPaciente)
                    .addComponent(lbCpfPaciente))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(inpCpfPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inpDoencaPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCadastro)
                    .addComponent(btnCancelar))
                .addGap(26, 26, 26))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCadPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadPacienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCadPacienteActionPerformed

    private void btnCadDoadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadDoadorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCadDoadorActionPerformed

    private void btnCadMedicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadMedicoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCadMedicoActionPerformed

    private void btnRelPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRelPacienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRelPacienteActionPerformed

    private void inpNomePacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inpNomePacienteActionPerformed
            // TODO add your handling code here:
    }//GEN-LAST:event_inpNomePacienteActionPerformed

    private void inpEmailPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inpEmailPacienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inpEmailPacienteActionPerformed

    private void inpIdadePacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inpIdadePacienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inpIdadePacienteActionPerformed

    private void cbSexoPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbSexoPacienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbSexoPacienteActionPerformed

    private void inpCpfPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inpCpfPacienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inpCpfPacienteActionPerformed

    private void cbTipoanguineoPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbTipoanguineoPacienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbTipoanguineoPacienteActionPerformed

    private void inpDoencaPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inpDoencaPacienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inpDoencaPacienteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FormPaciente().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar barMenu;
    private javax.swing.JMenuItem btnCadDoador;
    private javax.swing.JMenuItem btnCadMedico;
    private javax.swing.JMenuItem btnCadPaciente;
    private javax.swing.JButton btnCadastro;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JMenu btnMenu;
    private javax.swing.JMenuItem btnRelDoador;
    private javax.swing.JMenuItem btnRelMedico;
    private javax.swing.JMenuItem btnRelPaciente;
    private javax.swing.JMenu btnRelatorios;
    private javax.swing.JMenu cadMenu;
    private javax.swing.JComboBox<String> cbSexoPaciente;
    private javax.swing.JComboBox<String> cbTipoanguineoPaciente;
    private javax.swing.JTextField inpCpfPaciente;
    private javax.swing.JTextField inpDoencaPaciente;
    private javax.swing.JTextField inpEmailPaciente;
    private javax.swing.JTextField inpIdadePaciente;
    private javax.swing.JTextField inpNomePaciente;
    private javax.swing.JLabel lbCpfPaciente;
    private javax.swing.JLabel lbDoencaPaciente;
    private javax.swing.JLabel lbEmailPaciente;
    private javax.swing.JLabel lbIdadePaciente;
    private javax.swing.JLabel lbNomePaciente;
    private javax.swing.JLabel lbSexoPaciente;
    private javax.swing.JLabel lbTipoSanguineoPaciente;
    // End of variables declaration//GEN-END:variables
}
