// Luiz Felipe Feranandes Ramos - RA: 2767112
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author lipf2
 */
public class FormCadMedico extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FormCadMedico.class.getName());

    /**
     * Creates new form FormCadMedico
     */
    //MÉTODO SINGLETON
    private static FormCadMedico instancia;

    public static FormCadMedico getInstance() {
        if (instancia == null) {
            instancia = new FormCadMedico();
        }
        return instancia;
    }

    private FormCadMedico() {
        initComponents();
        // listeners
        btnCadastro.addActionListener(evt -> {
            Medico m = new Medico();
            m.setNome(inpNomeMedico.getText());
            try {
                int idade = Integer.parseInt(inpIdadelMedico.getText());
                m.setIdade(idade);
            } catch (NumberFormatException nfe) {
                javax.swing.JOptionPane.showMessageDialog(this, "Idade inválida (não é número)");
                return;
            } catch (IdadeInvalidaException ex) {
                javax.swing.JOptionPane.showMessageDialog(this, ex.getMessage());
                return;
            }
            m.setCpf(inpCpfMedico.getText());
            m.setSexo(cbSexoMedico.getSelectedItem().toString().charAt(0));
            m.setEmail(inpEmailMedico.getText());
            try {
                int crm = Integer.parseInt(inpCrmMedico.getText());
                m.setCrm(crm);
            } catch (NumberFormatException nfe) {
                javax.swing.JOptionPane.showMessageDialog(this, "CRM inválido (não é número)");
                return;
            } catch (CrmInvalidoException ex) {
                javax.swing.JOptionPane.showMessageDialog(this, ex.getMessage());
                return;
            }
            m.setEspecialidade(inpEspecialidadeMedico.getText());
            BDHospital.getInstance().inserirMedico(m);
            javax.swing.JOptionPane.showMessageDialog(this, "Médico cadastrado com sucesso!");
            // limpar
            inpNomeMedico.setText(""); inpIdadelMedico.setText(""); inpCpfMedico.setText(""); inpEmailMedico.setText(""); inpCrmMedico.setText(""); inpEspecialidadeMedico.setText("");
            cbSexoMedico.setSelectedIndex(0);
        });

        btnCancelar.addActionListener(evt -> {
            this.dispose();
            instancia = null;
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cbSexoMedico = new javax.swing.JComboBox<>();
        lbCpfMedico = new javax.swing.JLabel();
        inpCpfMedico = new javax.swing.JTextField();
        btnCadastro = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        lbEmailMedico = new javax.swing.JLabel();
        inpEmailMedico = new javax.swing.JTextField();
        lbNomeMedico = new javax.swing.JLabel();
        inpNomeMedico = new javax.swing.JTextField();
        lbTipoSanguineoMedico = new javax.swing.JLabel();
        lbIdadeMedico = new javax.swing.JLabel();
        lbEspecialidadeMedico = new javax.swing.JLabel();
        inpIdadelMedico = new javax.swing.JTextField();
        inpEspecialidadeMedico = new javax.swing.JTextField();
        lbSexoMedico = new javax.swing.JLabel();
        inpCrmMedico = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastrar Médico");

        cbSexoMedico.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "F", "M" }));
        cbSexoMedico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbSexoMedicoActionPerformed(evt);
            }
        });

        lbCpfMedico.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbCpfMedico.setText("CPF: 000.000.000-00");

        inpCpfMedico.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        inpCpfMedico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inpCpfMedicoActionPerformed(evt);
            }
        });

        btnCadastro.setText("Cadastrar");

        btnCancelar.setText("Cancelar");

        lbEmailMedico.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbEmailMedico.setText("Email:");

        inpEmailMedico.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        inpEmailMedico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inpEmailMedicoActionPerformed(evt);
            }
        });

        lbNomeMedico.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbNomeMedico.setText("Nome");

        inpNomeMedico.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        inpNomeMedico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inpNomeMedicoActionPerformed(evt);
            }
        });

        lbTipoSanguineoMedico.setText("CRM:");

        lbIdadeMedico.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbIdadeMedico.setText("Idade");

        lbEspecialidadeMedico.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbEspecialidadeMedico.setText("Especialidade:");

        inpIdadelMedico.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        inpIdadelMedico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inpIdadelMedicoActionPerformed(evt);
            }
        });

        inpEspecialidadeMedico.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        inpEspecialidadeMedico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inpEspecialidadeMedicoActionPerformed(evt);
            }
        });

        lbSexoMedico.setText("Sexo");

        inpCrmMedico.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        inpCrmMedico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inpCrmMedicoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnCadastro)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnCancelar)
                        .addGap(116, 116, 116))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbNomeMedico)
                                    .addComponent(inpNomeMedico, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lbIdadeMedico, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(inpIdadelMedico, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(lbSexoMedico)
                                        .addGap(26, 26, 26))
                                    .addComponent(cbSexoMedico, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbEmailMedico)
                                    .addComponent(inpEmailMedico, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbTipoSanguineoMedico)
                                    .addComponent(inpCrmMedico)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(inpCpfMedico, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lbCpfMedico)
                                        .addGap(83, 83, 83)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbEspecialidadeMedico)
                                    .addComponent(inpEspecialidadeMedico, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(21, 21, 21))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(67, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(lbNomeMedico)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(inpNomeMedico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(lbIdadeMedico)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(inpIdadelMedico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbSexoMedico)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbSexoMedico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbEmailMedico)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(inpEmailMedico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(inpCrmMedico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbTipoSanguineoMedico)
                        .addGap(32, 32, 32)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbEspecialidadeMedico)
                    .addComponent(lbCpfMedico))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(inpCpfMedico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inpEspecialidadeMedico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCadastro)
                    .addComponent(btnCancelar))
                .addGap(26, 26, 26))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbSexoMedicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbSexoMedicoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbSexoMedicoActionPerformed

    private void inpCpfMedicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inpCpfMedicoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inpCpfMedicoActionPerformed

    private void inpEmailMedicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inpEmailMedicoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inpEmailMedicoActionPerformed

    private void inpNomeMedicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inpNomeMedicoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inpNomeMedicoActionPerformed

    private void inpIdadelMedicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inpIdadelMedicoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inpIdadelMedicoActionPerformed

    private void inpEspecialidadeMedicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inpEspecialidadeMedicoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inpEspecialidadeMedicoActionPerformed

    private void inpCrmMedicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inpCrmMedicoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inpCrmMedicoActionPerformed

    public void sair() {
        int resp = javax.swing.JOptionPane.showConfirmDialog(this, "Deseja realmente sair?", "Saída", javax.swing.JOptionPane.YES_NO_OPTION);
        if (resp == javax.swing.JOptionPane.YES_OPTION) {
            this.dispose();
            instancia = null;
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> FormCadMedico.getInstance().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastro;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JComboBox<String> cbSexoMedico;
    private javax.swing.JTextField inpCpfMedico;
    private javax.swing.JTextField inpCrmMedico;
    private javax.swing.JTextField inpEmailMedico;
    private javax.swing.JTextField inpEspecialidadeMedico;
    private javax.swing.JTextField inpIdadelMedico;
    private javax.swing.JTextField inpNomeMedico;
    private javax.swing.JLabel lbCpfMedico;
    private javax.swing.JLabel lbEmailMedico;
    private javax.swing.JLabel lbEspecialidadeMedico;
    private javax.swing.JLabel lbIdadeMedico;
    private javax.swing.JLabel lbNomeMedico;
    private javax.swing.JLabel lbSexoMedico;
    private javax.swing.JLabel lbTipoSanguineoMedico;
    // End of variables declaration//GEN-END:variables
}
