// Luiz Felipe Feranandes Ramos - RA: 2767112
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author lipf2
 */
public class FormConsulta extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FormConsulta.class.getName());

    /**
     * Creates new form FormConsulta
     */
    //MÉTODO SINGLETON
    private static FormConsulta instancia;

    public static FormConsulta getInstance() {
        if (instancia == null) {
            instancia = new FormConsulta();
        }
        return instancia;
    }

    private FormConsulta() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnCancelar = new javax.swing.JButton();
        inpNomeMedico = new javax.swing.JTextField();
        lbNomePaciente = new javax.swing.JLabel();
        lbHoraConsulta = new javax.swing.JLabel();
        lbDataConsulta = new javax.swing.JLabel();
        inpNomePAciente = new javax.swing.JTextField();
        btnCadastro = new javax.swing.JButton();
        lbNomeMedico = new javax.swing.JLabel();
        inpDataConsulta = new javax.swing.JTextField();
        inpHoraConsulta = new javax.swing.JTextField();
        barmenu1 = new javax.swing.JMenuBar();
        btnMenu = new javax.swing.JMenu();
        cadMenu = new javax.swing.JMenu();
        btnCadPaciente = new javax.swing.JMenuItem();
        btnCadDoador = new javax.swing.JMenuItem();
        btnCadMedico = new javax.swing.JMenuItem();
        btnSair = new javax.swing.JMenuItem();
        btnRelatorios = new javax.swing.JMenu();
        btnRelPaciente = new javax.swing.JMenuItem();
        btnRelDoador = new javax.swing.JMenuItem();
        btnRelMedico = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnCancelar.setText("Cancelar");

        inpNomeMedico.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        inpNomeMedico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inpNomeMedicoActionPerformed(evt);
            }
        });

        lbNomePaciente.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbNomePaciente.setText("Paciente:");

        lbHoraConsulta.setText("Hora");

        lbDataConsulta.setText("Data");

        inpNomePAciente.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        inpNomePAciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inpNomePAcienteActionPerformed(evt);
            }
        });

        btnCadastro.setText("Cadastrar");

        lbNomeMedico.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbNomeMedico.setText("Médico:");

        inpDataConsulta.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        inpDataConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inpDataConsultaActionPerformed(evt);
            }
        });

        inpHoraConsulta.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        inpHoraConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inpHoraConsultaActionPerformed(evt);
            }
        });

        btnMenu.setText("Menu");
        btnMenu.setActionCommand("");

        cadMenu.setText("Cadastrar");

        btnCadPaciente.setText("Pacientes");
        btnCadPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadPacienteActionPerformed(evt);
            }
        });
        cadMenu.add(btnCadPaciente);

        btnCadDoador.setText("Doadores");
        btnCadDoador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadDoadorActionPerformed(evt);
            }
        });
        cadMenu.add(btnCadDoador);

        btnCadMedico.setText("Médicos");
        btnCadMedico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadMedicoActionPerformed(evt);
            }
        });
        cadMenu.add(btnCadMedico);

        btnMenu.add(cadMenu);

        btnSair.setText("Sair");
        btnMenu.add(btnSair);

        barmenu1.add(btnMenu);

        btnRelatorios.setText("Relatórios");

        btnRelPaciente.setText("Pacientes");
        btnRelPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRelPacienteActionPerformed(evt);
            }
        });
        btnRelatorios.add(btnRelPaciente);

        btnRelDoador.setText("Doadores");
        btnRelatorios.add(btnRelDoador);

        btnRelMedico.setText("Médicos");
        btnRelatorios.add(btnRelMedico);

        barmenu1.add(btnRelatorios);

        setJMenuBar(barmenu1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(99, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbNomeMedico)
                            .addComponent(inpNomeMedico, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(lbNomePaciente)
                                .addComponent(inpNomePAciente, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lbDataConsulta)
                                        .addComponent(inpDataConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(103, 103, 103)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(inpHoraConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lbHoraConsulta)))))
                        .addGap(84, 84, 84))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnCadastro)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnCancelar)
                        .addGap(119, 119, 119))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addComponent(lbNomeMedico)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inpNomeMedico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbNomePaciente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inpNomePAciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbDataConsulta)
                    .addComponent(lbHoraConsulta))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(inpDataConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inpHoraConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCadastro)
                    .addComponent(btnCancelar))
                .addGap(37, 37, 37))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCadPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadPacienteActionPerformed
        FormPaciente.getInstance().setVisible(true);
    }//GEN-LAST:event_btnCadPacienteActionPerformed

    private void btnCadDoadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadDoadorActionPerformed
        FormDoador.getInstance().setVisible(true);
    }//GEN-LAST:event_btnCadDoadorActionPerformed

    private void btnCadMedicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadMedicoActionPerformed
        FormMedico.getInstance().setVisible(true);
    }//GEN-LAST:event_btnCadMedicoActionPerformed

    private void btnRelPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRelPacienteActionPerformed
        java.util.List<Consulta> list = BDHospital.getInstance().listarConsultas();
        StringBuilder sb = new StringBuilder();
        for (Consulta cc : list) sb.append(cc.listar()).append('\n');
        javax.swing.JOptionPane.showMessageDialog(this, sb.length() == 0 ? "Nenhuma consulta cadastrada" : sb.toString());
    }//GEN-LAST:event_btnRelPacienteActionPerformed

    private void inpNomeMedicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inpNomeMedicoActionPerformed
        // no-op
    }//GEN-LAST:event_inpNomeMedicoActionPerformed

    private void inpNomePAcienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inpNomePAcienteActionPerformed
        // no-op
    }//GEN-LAST:event_inpNomePAcienteActionPerformed

    private void inpDataConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inpDataConsultaActionPerformed
        // no-op
    }//GEN-LAST:event_inpDataConsultaActionPerformed

    private void inpHoraConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inpHoraConsultaActionPerformed
        // no-op
    }//GEN-LAST:event_inpHoraConsultaActionPerformed

    private void btnCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastroActionPerformed
        String nomeMed = inpNomeMedico.getText();
        String nomePac = inpNomePAciente.getText();
        java.util.List<Medico> medicos = BDHospital.getInstance().listarMedicos();
        java.util.List<Paciente> pacientes = BDHospital.getInstance().listarPacientes();
        Medico medico = null;
        Paciente paciente = null;
        for (Medico m : medicos) if (m.getNome() != null && m.getNome().equalsIgnoreCase(nomeMed)) { medico = m; break; }
        for (Paciente p : pacientes) if (p.getNome() != null && p.getNome().equalsIgnoreCase(nomePac)) { paciente = p; break; }
        if (medico == null) { javax.swing.JOptionPane.showMessageDialog(this, "Médico não encontrado: " + nomeMed); return; }
        if (paciente == null) { javax.swing.JOptionPane.showMessageDialog(this, "Paciente não encontrado: " + nomePac); return; }
        Consulta c = new Consulta();
        c.setMedico(medico);
        c.setPaciente(paciente);
        c.setData(inpDataConsulta.getText());
        c.setHora(inpHoraConsulta.getText());
        BDHospital.getInstance().inserirConsulta(c);
        javax.swing.JOptionPane.showMessageDialog(this, "Consulta cadastrada com sucesso!");
        inpNomeMedico.setText(""); inpNomePAciente.setText(""); inpDataConsulta.setText(""); inpHoraConsulta.setText("");
    }//GEN-LAST:event_btnCadastroActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.dispose();
        instancia = null;
    }//GEN-LAST:event_btnCancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> FormConsulta.getInstance().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar barmenu1;
    private javax.swing.JMenuItem btnCadDoador;
    private javax.swing.JMenuItem btnCadMedico;
    private javax.swing.JMenuItem btnCadPaciente;
    private javax.swing.JButton btnCadastro;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JMenu btnMenu;
    private javax.swing.JMenuItem btnRelDoador;
    private javax.swing.JMenuItem btnRelMedico;
    private javax.swing.JMenuItem btnRelPaciente;
    private javax.swing.JMenu btnRelatorios;
    private javax.swing.JMenuItem btnSair;
    private javax.swing.JMenu cadMenu;
    private javax.swing.JTextField inpDataConsulta;
    private javax.swing.JTextField inpHoraConsulta;
    private javax.swing.JTextField inpNomeMedico;
    private javax.swing.JTextField inpNomePAciente;
    private javax.swing.JLabel lbDataConsulta;
    private javax.swing.JLabel lbHoraConsulta;
    private javax.swing.JLabel lbNomeMedico;
    private javax.swing.JLabel lbNomePaciente;
    // End of variables declaration//GEN-END:variables
}
