/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author lipf2
 */
public class FormDoador extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FormDoador.class.getName());

    /**
     * Creates new form FormDoador
     */
    public FormDoador() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbIdadeDoador = new javax.swing.JLabel();
        inpDoencaDoador = new javax.swing.JTextField();
        inpIdadeDoador = new javax.swing.JTextField();
        lbSexoDoador = new javax.swing.JLabel();
        cbSexoDoador = new javax.swing.JComboBox<>();
        lbCpfDoador = new javax.swing.JLabel();
        inpCpfDoador = new javax.swing.JTextField();
        btnCadastro = new javax.swing.JButton();
        lbNomeDoador = new javax.swing.JLabel();
        btnCancelar = new javax.swing.JButton();
        inpNomeDoador = new javax.swing.JTextField();
        cbTipoanguineoDoador = new javax.swing.JComboBox<>();
        lbEmailDoador = new javax.swing.JLabel();
        lbTipoSanguineoDoador = new javax.swing.JLabel();
        inpEmailDoador = new javax.swing.JTextField();
        lbDoencaDoador = new javax.swing.JLabel();
        barMenu = new javax.swing.JMenuBar();
        btnMenu = new javax.swing.JMenu();
        cadMenu = new javax.swing.JMenu();
        btnCadPaciente = new javax.swing.JMenuItem();
        btnCadDoador = new javax.swing.JMenuItem();
        btnCadMedico = new javax.swing.JMenuItem();
        btnRelatorios = new javax.swing.JMenu();
        btnRelPaciente = new javax.swing.JMenuItem();
        btnRelDoador = new javax.swing.JMenuItem();
        btnRelMedico = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbIdadeDoador.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbIdadeDoador.setText("Idade");

        inpDoencaDoador.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        inpDoencaDoador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inpDoencaDoadorActionPerformed(evt);
            }
        });

        inpIdadeDoador.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        inpIdadeDoador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inpIdadeDoadorActionPerformed(evt);
            }
        });

        lbSexoDoador.setText("Sexo");

        cbSexoDoador.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "F", "M" }));
        cbSexoDoador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbSexoDoadorActionPerformed(evt);
            }
        });

        lbCpfDoador.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbCpfDoador.setText("CPF: 000.000.000-00");

        inpCpfDoador.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        inpCpfDoador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inpCpfDoadorActionPerformed(evt);
            }
        });

        btnCadastro.setText("Cadastrar");

        lbNomeDoador.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbNomeDoador.setText("Nome");

        btnCancelar.setText("Cancelar");

        inpNomeDoador.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        inpNomeDoador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inpNomeDoadorActionPerformed(evt);
            }
        });

        cbTipoanguineoDoador.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A+", "A-", "B+", "B-", "AB+", "AB-", "O+", "O-" }));
        cbTipoanguineoDoador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbTipoanguineoDoadorActionPerformed(evt);
            }
        });

        lbEmailDoador.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbEmailDoador.setText("Email:");

        lbTipoSanguineoDoador.setText("Tipo Sanguineo:");

        inpEmailDoador.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        inpEmailDoador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inpEmailDoadorActionPerformed(evt);
            }
        });

        lbDoencaDoador.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbDoencaDoador.setText("Doença:");

        btnMenu.setText("Menu");
        btnMenu.setActionCommand("");

        cadMenu.setText("Cadastrar");

        btnCadPaciente.setText("Pacientes");
        btnCadPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadPacienteActionPerformed(evt);
            }
        });
        cadMenu.add(btnCadPaciente);

        btnCadDoador.setText("Doadores");
        btnCadDoador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadDoadorActionPerformed(evt);
            }
        });
        cadMenu.add(btnCadDoador);

        btnCadMedico.setText("Médicos");
        btnCadMedico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadMedicoActionPerformed(evt);
            }
        });
        cadMenu.add(btnCadMedico);

        btnMenu.add(cadMenu);

        barMenu.add(btnMenu);

        btnRelatorios.setText("Relatórios");

        btnRelPaciente.setText("Pacientes");
        btnRelPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRelPacienteActionPerformed(evt);
            }
        });
        btnRelatorios.add(btnRelPaciente);

        btnRelDoador.setText("Doadores");
        btnRelatorios.add(btnRelDoador);

        btnRelMedico.setText("Médicos");
        btnRelatorios.add(btnRelMedico);

        barMenu.add(btnRelatorios);

        setJMenuBar(barMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(11, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnCadastro)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnCancelar)
                        .addGap(116, 116, 116))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbNomeDoador)
                                    .addComponent(inpNomeDoador, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lbIdadeDoador, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(inpIdadeDoador, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(lbSexoDoador)
                                        .addGap(26, 26, 26))
                                    .addComponent(cbSexoDoador, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbEmailDoador)
                                    .addComponent(inpEmailDoador, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbTipoSanguineoDoador)
                                    .addComponent(cbTipoanguineoDoador, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(inpCpfDoador, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lbCpfDoador)
                                        .addGap(83, 83, 83)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbDoencaDoador)
                                    .addComponent(inpDoencaDoador, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(21, 21, 21))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(lbNomeDoador)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(inpNomeDoador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(lbIdadeDoador)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(inpIdadeDoador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbSexoDoador)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbSexoDoador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbEmailDoador)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(inpEmailDoador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbTipoSanguineoDoador)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbTipoanguineoDoador, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbDoencaDoador)
                    .addComponent(lbCpfDoador))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(inpCpfDoador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inpDoencaDoador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCadastro)
                    .addComponent(btnCancelar))
                .addGap(26, 26, 26))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCadPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadPacienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCadPacienteActionPerformed

    private void btnCadDoadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadDoadorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCadDoadorActionPerformed

    private void btnCadMedicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadMedicoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCadMedicoActionPerformed

    private void btnRelPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRelPacienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRelPacienteActionPerformed

    private void inpDoencaDoadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inpDoencaDoadorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inpDoencaDoadorActionPerformed

    private void inpIdadeDoadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inpIdadeDoadorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inpIdadeDoadorActionPerformed

    private void cbSexoDoadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbSexoDoadorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbSexoDoadorActionPerformed

    private void inpCpfDoadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inpCpfDoadorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inpCpfDoadorActionPerformed

    private void inpNomeDoadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inpNomeDoadorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inpNomeDoadorActionPerformed

    private void cbTipoanguineoDoadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbTipoanguineoDoadorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbTipoanguineoDoadorActionPerformed

    private void inpEmailDoadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inpEmailDoadorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inpEmailDoadorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FormDoador().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar barMenu;
    private javax.swing.JMenuItem btnCadDoador;
    private javax.swing.JMenuItem btnCadMedico;
    private javax.swing.JMenuItem btnCadPaciente;
    private javax.swing.JButton btnCadastro;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JMenu btnMenu;
    private javax.swing.JMenuItem btnRelDoador;
    private javax.swing.JMenuItem btnRelMedico;
    private javax.swing.JMenuItem btnRelPaciente;
    private javax.swing.JMenu btnRelatorios;
    private javax.swing.JMenu cadMenu;
    private javax.swing.JComboBox<String> cbSexoDoador;
    private javax.swing.JComboBox<String> cbTipoanguineoDoador;
    private javax.swing.JTextField inpCpfDoador;
    private javax.swing.JTextField inpDoencaDoador;
    private javax.swing.JTextField inpEmailDoador;
    private javax.swing.JTextField inpIdadeDoador;
    private javax.swing.JTextField inpNomeDoador;
    private javax.swing.JLabel lbCpfDoador;
    private javax.swing.JLabel lbDoencaDoador;
    private javax.swing.JLabel lbEmailDoador;
    private javax.swing.JLabel lbIdadeDoador;
    private javax.swing.JLabel lbNomeDoador;
    private javax.swing.JLabel lbSexoDoador;
    private javax.swing.JLabel lbTipoSanguineoDoador;
    // End of variables declaration//GEN-END:variables
}
